import React, { Component } from 'react';

class Country extends Component {

  render() {
    return (
      <div>
        <p className="title marginBottom-small">Country</p>
        <select>
          <option value="volvo">Afghanistan</option>
          <option value="saab">Aland Islands</option>
          <option value="mercedes">Albania</option>
          <option value="audi">Algeria</option>
          <option value="audi">Andorra</option>
          <option value="audi">Angola</option>
          <option value="audi">Anguilla</option>
          <option value="audi">Antigua And Barbuda</option>
          <option value="audi">Argentina</option>
          <option value="audi">Armenia</option>
          <option value="audi">Aruba</option>
          <option value="audi">Australia</option>
          <option value="audi">Austria</option>
          <option value="audi">Azerbaijan</option>
          <option value="audi">Bahamas</option>
          <option value="audi">Bahrain</option>
          <option value="audi">Bangladesh</option>
          <option value="audi">Barbados</option>
          <option value="audi">Belarus</option>
          <option value="audi">Belgium</option>
          <option value="audi">Belize</option>
          <option value="audi">Benin</option>
          <option value="audi">Bermuda</option>
          <option value="audi">Bhutan</option>
          <option value="audi">Bolivia</option>
          <option value="audi">Bosnia And Herzegovina</option>
          <option value="audi">Botswana</option>
          <option value="audi">Bouvet Island</option>
          <option value="audi">Brazil</option>
          <option value="audi">British Indian Ocean Territory</option>
          <option value="audi">Brunei</option>
          <option value="audi">Bulgaria</option>
          <option value="audi">Burkina Faso</option>
          <option value="audi">Burundi</option>
          <option value="audi">Cambodia</option>
          <option value="audi">Canada</option>
          <option value="audi">Cape Verde</option>
          <option value="audi">Cayman Islands</option>
          <option value="audi">Central African Republic</option>
          <option value="audi">Chad</option>
          <option value="audi">Chile</option>
          <option value="audi">China</option>
          <option value="audi">Christmas Island</option>
          <option value="audi">Cocos (Keeling) Islands</option>
          <option value="audi">Colombia</option>
          <option value="audi">Comoros</option>
          <option value="audi">Congo</option>
          <option value="audi">Congo, The Democratic Republic of the Congo</option>
          <option value="audi">Cook Islands</option>
          <option value="audi">Costa Rica</option>
          <option value="audi">Croatia</option>
          <option value="audi">Cuba</option>
          <option value="audi">Curaçau</option>
          <option value="audi">Cyprus</option>
          <option value="audi">Czech Republic</option>
          <option value="audi">Côte k'Ivoire</option>
          <option value="audi">Denmark</option>
          <option value="audi">Dijbouti</option>
          <option value="audi">Dominica</option>
          <option value="audi">Dominican Republic</option>
          <option value="audi">Ecuador</option>
          <option value="audi">Egypt</option>
          <option value="audi">El Salvador</option>
          <option value="audi">Equatorial Guinea</option>
          <option value="audi">Eritrea</option>
          <option value="audi">Estonia</option>
          <option value="audi">Ethiopia</option>
          <option value="audi">Falkland Islands (Maldives)</option>
          <option value="audi">Faroe Islands</option>
          <option value="audi">Fiji</option>
          <option value="audi">Finland</option>
          <option value="audi">France</option>
          <option value="audi">French Guiana</option>
          <option value="audi">French Polynesia</option>
          <option value="audi">French Southern Territories</option>
          <option value="audi">Gabon</option>
          <option value="audi">Gambia</option>
          <option value="audi">Georgia</option>
          <option value="audi">Germany</option>
          <option value="audi">Ghana</option>
          <option value="audi">Gibraltar</option>
          <option value="audi">Greece</option>
          <option value="audi">Greenland</option>
          <option value="audi">Grenada</option>
          <option value="audi">Guadeloupe</option>
          <option value="audi">Guatemala</option>
          <option value="audi">Guernsey</option>
          <option value="audi">Guinea</option>
          <option value="audi">Guinea Bissau</option>
          <option value="audi">Guyana</option>
          <option value="audi">Haiti</option>
          <option value="audi">Heard Island And Mcdonald Islands</option>
          <option value="audi">Holy See (Vatican City State)</option>
          <option value="audi">Honduras</option>
          <option value="audi">Hong Kong</option>
          <option value="audi">Hungary</option>
          <option value="audi">Iceland</option>
          <option value="audi">India</option>
          <option value="audi">Indonesia</option>
          <option value="audi">Iran, Islamic Republic Of</option>
          <option value="audi">Iraq</option>
          <option value="audi">Ireland</option>
          <option value="audi">Isle Of Man</option>
          <option value="audi">Israel</option>
          <option value="audi">Italy</option>
          <option value="audi">Jamaica</option>
          <option value="audi">Japan</option>
          <option value="audi">Jersey</option>
          <option value="audi">Jordan</option>
          <option value="audi">Kazakhstan</option>
          <option value="audi">Kenya</option>
          <option value="audi">Kiribati</option>
          <option value="audi">Korea, Democratic People's Republic Of</option>
          <option value="audi">Kosovo</option>
          <option value="audi">Kuwait</option>
          <option value="audi">Kyrgyzstan</option>
          <option value="audi">Lao People's Democratic Republic</option>
          <option value="audi">Latvia</option>
          <option value="audi">Lebanon</option>
          <option value="audi">Lesotho</option>
          <option value="audi">Liberia</option>
          <option value="audi">Libyan Arab Jamahiriya</option>
          <option value="audi">Liechtenstein</option>
          <option value="audi">Lithuania</option>
          <option value="audi">Luxembourg</option>
          <option value="audi">Macao</option>
          <option value="audi">Macedonia, Republic Of</option>
          <option value="audi">Madagascar</option>
          <option value="audi">Malawi</option>
          <option value="audi">Malaysia</option>
          <option value="audi">Maldives</option>
          <option value="audi">Mali</option>
          <option value="audi">Malta</option>
          <option value="audi">Martinique</option>
          <option value="audi">Mauritania</option>
          <option value="audi">Mauritius</option>
          <option value="audi">Mayotte</option>
          <option value="audi">Mexico</option>
          <option value="audi">Moldova, Republic Of</option>
          <option value="audi">Monaco</option>
          <option value="audi">Mongolia</option>
          <option value="audi">Montenegro</option>
          <option value="audi">Montserrat</option>
          <option value="audi">Morocco</option>
          <option value="audi">Mozambique</option>
          <option value="audi">Myanmar</option>
          <option value="audi">Nambia</option>
          <option value="audi">Nauru</option>
          <option value="audi">Nepal</option>
          <option value="audi">Netherlands</option>
          <option value="audi">Netherlands Antilles</option>
          <option value="audi">New Caledonia</option>
          <option value="audi">New Zealand</option>
          <option value="audi">Nicaragua</option>
          <option value="audi">Niger</option>
          <option value="audi">Nigeria</option>
          <option value="audi">Niue</option>
          <option value="audi">Norfolk Island</option>
          <option value="audi">Norway</option>
          <option value="audi">Oman</option>
          <option value="audi">Pakistan</option>
          <option value="audi">Palestinian Territory, Occupied</option>
          <option value="audi">Panama</option>
          <option value="audi">Papua New Guinea</option>
          <option value="audi">Paraguay</option>
          <option value="audi">Peru</option>
          <option value="audi">Philippines</option>
          <option value="audi">Pitcairn</option>
          <option value="audi">Poland</option>
          <option value="audi">Portugal</option>
          <option value="audi">Qatar</option>
          <option value="audi">Republic of Cameroon</option>
          <option value="audi">Reunion</option>
          <option value="audi">Romania</option>
          <option value="audi">Russia</option>
          <option value="audi">Rwanda</option>
          <option value="audi">Saint Barthélemy</option>
          <option value="audi">Saint Helena</option>
          <option value="audi">Saint Kitts And Miquelon</option>
          <option value="audi">Samoa</option>
          <option value="audi">San Marino</option>
          <option value="audi">Sao Tome And Principe</option>
          <option value="audi">Saudi Arabia</option>
          <option value="audi">Senegal</option>
          <option value="audi">Serbia</option>
          <option value="audi">Seychelles</option>
          <option value="audi">Sierra Leone</option>
          <option value="audi">Singapore</option>
          <option value="audi">Sint Maarten</option>
          <option value="audi">Slovakia</option>
          <option value="audi">Slovenia</option>
          <option value="audi">Solomon Islands</option>
          <option value="audi">Somalia</option>
          <option value="audi">South Africa</option>
          <option value="audi">South Georgia And The South Sandwich Islands</option>
          <option value="audi">South Korea</option>
          <option value="audi">Spain</option>
          <option value="audi">Sri Lanka</option>
          <option value="audi">St. Vincent</option>
          <option value="audi">Sudan</option>
          <option value="audi">Suriname</option>
          <option value="audi">Svalbard And Jan Mayen</option>
          <option value="audi">Swaziland</option>
          <option value="audi">Sweden</option>
          <option value="audi">Switzerland</option>
          <option value="audi">Syria</option>
          <option value="audi">Taiwan</option>
          <option value="audi">Tajikistan</option>
          <option value="audi">Tanzania, United Republic Of</option>
          <option value="audi">Thailand</option>
          <option value="audi">Timor Leste</option>
          <option value="audi">Togo</option>
          <option value="audi">Tokelau</option>
          <option value="audi">Tonga</option>
          <option value="audi">Trinidad and Tobago</option>
          <option value="audi">Tunisia</option>
          <option value="audi">Turkey</option>
          <option value="audi">Turkmenistan</option>
          <option value="audi">Turks and Caicos Islands</option>
          <option value="audi">Tuvalu</option>
          <option value="audi">Uganda</option>
          <option value="audi">Ukraine</option>
          <option value="audi">United Arab Emirates</option>
          <option value="audi">United Kingdom</option>
          <option value="audi">United States</option>
          <option value="audi">United States Minor Outlying Islands</option>
          <option value="audi">Uruguay</option>
          <option value="audi">Uzbekistan</option>
          <option value="audi">Vanuatu</option>
          <option value="audi">Venezuela</option>
          <option value="audi">Vietnam</option>
          <option value="audi">Virgin Islands, British</option>
          <option value="audi">Wallis And Futuna</option>
          <option value="audi">Western Sahara</option>
          <option value="audi">Yemen</option>
          <option value="audi">Zambia</option>
          <option value="audi">Zimbabwe</option>
        </select>
      </div>
    );
  }
}

export default Country;